### ISSUE TITLE
Multitwitch/multiple windows/basic GUI

### ISSUE THREAD

**Issue by estathop** [patrickdappollonio/twitch-stream#1]
It would be awesome if somehow twitch-stream could support multitwitch or at least run multiple instances of different streams in different vlc windows. That's not possible through cmd. Furthermore, a basic GUI would be wonderful, too.

**Comment by patrickdappollonio** [comment]
I was thinking about a GUI too. I just need to find a library who works and who can create user interfaces on both Mac and Windows. 

Regarding supporting multiple screens, that's already available: you just need to execute the app with as many instances as you like. At least in Mac OS X, it will open several VLC windows with the correspondent stream on it. It might probably be a good fit to just pass several parameters to the app and let the app open as many VLC instances as possible.

I'll keep this ticket open as an enhancement so we can keep track of it in the future!

**Comment by estathop** [comment]
In windows 8.1 prof, I think you can't have multiple instances because you execute it through cmd and you can't open a new cmd to run it there. While the app is running you can't do anything else on cmd. The basic GUI would be a window just asking for the   Twitch user you would like to watch and perhaps a choice on which program you want to execute other than vlc. For Europe the average delay is around 17 seconds in contrary with live streamer which is more than 30 seconds

Στάλθηκε από το iPhone μου

16 Μαϊ 2015, 23:05, ο/η patrickdappollonio notifications@github.com έγραψε:

**Comment by patrickdappollonio** [comment]
> In windows 8.1 prof, I think you can't have multiple instances because you execute it through cmd and you can't open a new cmd to run it there. While the app is running you can't do anything else on cmd. 

This is intended, and it is a side effect of Go: because it's a cross platform language, they're still getting through the possibility of process forking. On Mac OS X, the code run just fine if I want to decouple the VLC screen from the Terminal itself. It's in Windows where the problem persists. Still, I'll look for an alternative.

As a side note, on Windows, is the user who needs to allow multiple instances on VLC, while on Mac, the `twitch-stream` app already handles the multi-screen issue. This is a VLC problem / feature and I cannot control it.

> The basic GUI would be a window just asking for the Twitch user you would like to watch and perhaps a choice on which program you want to execute other than vlc.

I agree with the GUI. I have a cross opinion on the program selection though: the Twitch stream is based on the m3u8 media, which isn't available on all media programs, so using VLC is an option that definitely works, but I can not say the same of other apps. I could offer the possibility to select what app could possibly run the stream, but if the user choose a software who cannot run the app, they'll probably blame this app. That could be contradictory, but it happens.

> For Europe the average delay is around 17 seconds in contrary with live streamer which is more than 30 seconds. 

I couldn't get this: you mean, getting a stream with `twitch-stream` is faster than `livestreamer`?

Thanks a lot for your suggestions. I'll try to see what options I have available and bring a few solutions to the table.

**Comment by patrickdappollonio** [comment]
## Update to the multi-stream enhancement

Hello!

The latest update brought nice stuff. Essentially, now VLC includes in the settings an option to [enable multiple instances of VLC](https://wiki.videolan.org/How_to_play_multiple_instances_of_VLC/) and we will take advantage of it. Now, if you run `twitch-stream patrickdappollonio` it will open a Window and as soon as possible, the app `twitch-stream` will close but the VLC window will be still open. 

In order to see multiple streams, you only need to call `twitch-stream username` several times with the "multiple instances of VLC" option enabled in VLC settings.

**Sadly this VLC feature is only available for Windows and Linux users** (yes! now `twitch-stream` supports Linux users out of the box!). This is not a problem within `twitch-stream` itself but more like a VLC feature.

Soon I'll provide executables for the new version in the [releases page](https://github.com/patrickdappollonio/twitch-stream/releases).

This is now closed!
